### ISSUE TITLE
[error] script [ cc bot ] stopped with error in line 1047

### ISSUE THREAD

**Issue by joejoy0243** [greydust/CC-Bot#7]
hi 你好

Win 7 64位元
V 3.5.1.0

請問這個錯誤訊息是怎麼了? 我和朋友都卡在這 QAQ
有自己抓圖了

[info] HotkeyManager: add Hotkey: ALT F1 (112, 8)
[info] HotkeyManager: add Hotkey: ALT 1 (49, 8)
[info] HotkeyManager: add Hotkey: ALT 2 (50, 8)

[error] script [ cc bot ] stopped with error in line 1047
[error] TypeError ( observeJ(): expected 3 args; got 2 )
[error] --- Traceback --- error source first line: module ( function ) statement 70: main ( StartObserve ) self.triggerRegion.observe(FOREVER, True)
67: main ( __init__ ) self.StartObserve()
146: main ( StartMachine ) self.observers[key] = RegionObserver(self, BotMachine.GlobalObserveDefinition[key].CalculateRegionInMachine(self.leftTop), BotMachine.GlobalObserveDefinition[key].image, BotMachine.GlobalObserveDefinition[key].function, BotMachine.GlobalObserveDefinition[key].repeat)
[error] --- Traceback --- end --------------

**Comment by greydust** [comment]
這應該是SikiliX 1.1.1會出現的問題, 請使用1.1.0版
網址: https://launchpad.net/sikuli/sikulix/1.1.0

**Comment by joejoy0243** [comment]
感謝! 可以正常執行了

不過執行bot視窗縮小後 遊戲沒有任何反應 Q____Q

[info] HotkeyManager: add Hotkey: ALT F1 (112, 8)
[info] HotkeyManager: add Hotkey: ALT 1 (49, 8)
[info] HotkeyManager: add Hotkey: ALT 2 (50, 8)

BotMachine.__init__: index = 0, leftTop = L(19,14)@S(0)[0,0 1920x1080]
BotMachine.__init__: index = 1, leftTop = L(18,474)@S(0)[0,0 1920x1080]

**Comment by greydust** [comment]
按照log來看已經有抓到兩個模擬器的視窗了, 要讓bot開始動的話目前有三個條件
1. 在Touch Screen畫面抓到Touch Screen的話, 會自動開始跑新手教學
2. 在はじまりの村的話, 會按照設定開始自動打關卡 (目前1.1.6.0的設定, 如果你們是抓舊版的話就要看一下cc_bot_config裡面Stages和StageRegionImage是設定在那了. 或者是直接重抓1.1.6.0也可以)
3. 在賭場賭大小的畫面的話 (進入盤面以後), 會自動開始賭大小

如果已經在上面三個畫面的其中一個卻沒有開始動的話, 可能是解析度和dpi的問題 (720x405, 160dpi)

如果解析度有設對但還是不會動, 可以將螢幕截個圖上傳, 我會再試試看是那邊有問題

**Comment by joejoy0243** [comment]
嗯 測起來 感覺是抓不到遊戲內對應的圖
不過解析度和 DPI 應該沒有設錯 再麻煩你確認看看

![20160612](https://cloud.githubusercontent.com/assets/19876864/15990723/6832451a-30cf-11e6-891a-c4c9f0e8946d.jpg)

**Comment by greydust** [comment]
就圖片來說, 它應該有點擊Touch Screen但是沒有點擊同意する?

稍微檢查了一下, 我猜測問題可能是出在你抓完左上角的圖以後, 沒有再點進去設定目標偏移

如下圖所示
![image](https://cloud.githubusercontent.com/assets/7523684/15990822/2ac082ac-30d2-11e6-8f5c-a0eae5334183.png)

![image](https://cloud.githubusercontent.com/assets/7523684/15990825/583ffd66-30d2-11e6-8ec3-31ff0662bb5a.png)

如果還是不行的話, 可能要麻煩你試試看賭場以及打關卡是否能正常運作了. 理論上如果已經會去點Touch Screen, 應該只有我上面寫的這個問題才對.

**Comment by joejoy0243** [comment]
其實 Touch Screen 是我自己點的 XDDDDD!

謝謝你! 正在運作中 我再觀察後續的狀況：）

**Comment by joejoy0243** [comment]
Hi 不好意思打擾你
運行一天之後 今天突然怎麼設置都沒有動靜了 不知道是哪裡出了問題

![20160615](https://cloud.githubusercontent.com/assets/19876864/16062108/a8855274-32c3-11e6-9259-4f220f450fff.jpg)

**Comment by greydust** [comment]
比對了一下圖片應該是沒什麼問題, 目前能想到的應該是以下這些可能

1. 啟動Sikuli的時候是否是使用管理員身份啟動?
2. 是否是從Touch Screen的畫面讓它開始跑新手教學? (即使跑到一半斷掉, 還是要回到Touch Screen讓它重新登入才會判斷要跑新手教學)

**Comment by joejoy0243** [comment]
感謝! 原來是沒有從Touch Screen的畫面開始執行的緣故!
